### ISSUE TITLE
Failed to fetch https://example.com/rss with message 'not in gzip format'

### ISSUE THREAD

**Issue by wojtek1171** [YunoHost-Apps/huginn_ynh#32]
Almost all of my sources runs with that error. Seems to be related to one of the issue from main repository handled 5 days ago (18th Nov) ago. Current YNH release is from (17th Nov)

https://github.com/huginn/huginn/pull/3468

`[00:00:00] ERROR -- : Failed to fetch https://example.com/rss with message 'not in gzip format': ["/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-gzip-3.0.2/lib/faraday/gzip/middleware.rb:69:in `initialize'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-gzip-3.0.2/lib/faraday/gzip/middleware.rb:69:in `new'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-gzip-3.0.2/lib/faraday/gzip/middleware.rb:69:in `uncompress_gzip'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-gzip-3.0.2/lib/faraday/gzip/middleware.rb:107:in `block in processors'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-gzip-3.0.2/lib/faraday/gzip/middleware.rb:60:in `reset_body'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-gzip-3.0.2/lib/faraday/gzip/middleware.rb:43:in `block in call'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-2.12.1/lib/faraday/response.rb:42:in `on_complete'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-gzip-3.0.2/lib/faraday/gzip/middleware.rb:42:in `call'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-2.12.1/lib/faraday/request/url_encoded.rb:25:in `call'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-multipart-1.0.4/lib/faraday/multipart/middleware.rb:28:in `call'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-follow_redirects-0.3.0/lib/faraday/follow_redirects/middleware.rb:77:in `perform_with_redirection'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-follow_redirects-0.3.0/lib/faraday/follow_redirects/middleware.rb:65:in `call'", "/var/www/huginn/app/concerns/web_request_concern.rb:25:in `call'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-2.12.1/lib/faraday/rack_builder.rb:152:in `build_response'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-2.12.1/lib/faraday/connection.rb:452:in `run_request'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/faraday-2.12.1/lib/faraday/connection.rb:200:in `get'", "/var/www/huginn/app/models/agents/rss_agent.rb:166:in `block in check_urls'", "/var/www/huginn/app/models/agents/rss_agent.rb:165:in `each'", "/var/www/huginn/app/models/agents/rss_agent.rb:165:in `check_urls'", "/var/www/huginn/app/models/agents/rss_agent.rb:156:in `check'", "/var/www/huginn/app/concerns/dry_runnable.rb:33:in `dry_run!'", "/var/www/huginn/app/controllers/agents/dry_runs_controller.rb:41:in `create'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/actionpack-6.1.7.10/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/actionpack-6.1.7.10/lib/abstract_controller/base.rb:228:in `process_action'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/actionpack-6.1.7.10/lib/action_controller/metal/rendering.rb:30:in `process_action'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/actionpack-6.1.7.10/lib/abstract_controller/callbacks.rb:42:in `block in process_action'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.10/lib/active_support/callbacks.rb:106:in `run_callbacks'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/actionpack-6.1.7.10/lib/abstract_controller/callbacks.rb:41:in `process_action'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/actionpack-6.1.7.10/lib/action_controller/metal/rescue.rb:22:in `process_action'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/actionpack-6.1.7.10/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'", "/var/www/huginn/vendor/bundle/ruby/3.2.0/gems/activesuppor`

EDIT: Applying changes from these pull request manually fixed it for now https://github.com/huginn/huginn/pull/3468/files

**Comment by wojtek1171** [comment]
Fixed by https://github.com/YunoHost-Apps/huginn_ynh/pull/33
